# Display a box
print(" Please enter a character to represent the robot eyes")
eyes = input (" enter the caractere here:  ")
print("##########")
print("# --   --#")
print("#"" "+eyes+"   "+eyes+"  #")
print("#        #     #")
print("#   -O- #     #")
print("##########    #")
print("##########  #")
print("############")
print("##########")
print("##########")
print(" ##    ##")
print(" ##    ##")
print(" ##    ##")
